config/routes.rb
Rails.application.routes.draw do
  get 'questions/edit'
  root 'histories#index'
  
  resources :histories do
    collection do
      get 'search'
    end
    resources :questions
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/history.rb
class History < ApplicationRecord
    has_many :questions, dependent: :destroy
    
    mount_uploader :image, ImageUploader
  
    validates :treasurer, presence: true
    validates :payee, presence: true
    validates :title, presence: true
    # validates :image, :file_size => {:maximum => 2.megabytes}

    enum status: {income: 0, outcome: 1}
    
    def self.search(params)
      histories = History.all
      histories = histories.where(["title LIKE ?", "%#{params[:title]}%"]) if params[:title].present?
      histories = histories.where(["payee LIKE ?", "%#{params[:payee]}%"]) if params[:payee].present?
      histories = histories.where(["treasurer LIKE ?", "%#{params[:treasurer]}%"]) if params[:treasurer].present?
      histories = histories.where(status: params[:status]) if params[:status].present?
      histories = histories.where(price: params[:price]) if params[:price].present?
      # histories = histories.where("? <= start_received_day", Time.zone.parse(params[:start_received_day] + '00:00:00')) if params[:start_received_day].present?
      # histories = histories.where("? <= finish_received_day", Time.zone.parse(params[:finish_received_day] + '23:59:59')) if params[:finish_received_day].present?
      # histories = histories.where("? <= start_return_day", Time.zone.parse(params[:start_return_day] + '00:00:00')) if params[:start_return_day].present?
      # histories = histories.where("? <= finish_return_day", Time.zone.parse(params[:finish_return_day] + '23:59:59')) if params[:finish_return_day].present?
      return histories
    end
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :history
  validates :content, presence: true
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/histories_controller.rb
class HistoriesController < ApplicationController
  before_action :set_history, only: [:show, :edit, :update, :destroy]
  
  def index
    @histories = History.all
    @total_income = History.where(status: History.statuses[:income]).sum(:price)
    @total_outcome = History.where(status: History.statuses[:outcome]).sum(:price)
    @total_price = @total_income - @total_outcome
  end
  
  def search
    @histories = params[:search].nil? ? History.search(history_params) : History.search(history_search_params)
  end

  def show
    @question = Question.new
  end

  def new
    @history = History.new
  end
  
  def create
    @history = History.new(history_create_params)
    if @history.save
      redirect_to root_path, notice: '登録に成功しました!'
    else
      flash[:alert] = '作成に失敗しました。再度やり直して下さい'
      render :new
    end
  end

  def edit
  end
  
  def update
    if @history.update(history_create_params)
      redirect_to root_path, notice: '編集しました!'
    else
      flash[:alert] = '編集に失敗しました'
      render :edit
    end
  end
  
  def destroy
    @history.destroy
    redirect_to root_path, notice: '削除しました!'
  end
  
  private
    def set_history
      @history = History.find(params[:id])
    end
    
    def history_params
      params.permit(:payee, :treasurer, :title, :description, :price, :category, :status, :start_received_day, :finish_received_day, :start_return_day, :finish_return_day, :image)
    end
  
    def history_search_params
      params.require(:search).permit(:payee, :treasurer, :title, :description, :price, :category, :status, :start_received_day, :finish_received_day, :start_return_day, :finish_return_day, :image)
    end
    
    def history_create_params
      params.require(:history).permit(:payee, :treasurer, :received_day, :return_day, :title, :description, :price, :category, :status, :image)
    end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  
  def create
    @history = History.find(params[:history_id])
    @question = Question.new
    if @question.update(question_params)
      redirect_to history_path(@history), notice: '作成しました!'
    else
      redirect_to history_path(@history), alert: '作成に失敗しました。再度やり直して下さい'
    end
  end
  
  def edit
    @history = History.find(params[:history_id])
    @question = @history.questions.find(params[:id])
  end
  
  def update
    @history = History.find(params[:history_id])
    @question = @history.questions.find(params[:id])
    if @question.update(question_params)
      redirect_to history_path(@history), notice: '作成しました!'
    else
      flash[:alert] = '作成に失敗しました。再度やり直して下さい!'
      render :edit
    end
  end
  
  def destroy
    @history = History.find(params[:history_id])
    @question = @history.questions.find(params[:id])
    @question.destroy
    redirect_to history_path(@history), notice: '削除しました!'
  end
  
  private
    def question_params
      params.require(:question).permit(:history_id, :name, :title, :content, :status)
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/histories_helper.rb
module HistoriesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/histories/_form.html.erb
<script>
$(function(){
  <% if @history.status == 'income' %>
    $('#return_day_area').hide();
  <% else %>
    $('#return_day_area').show();
  <% end %>
})
</script>

<%= form_with model: @history, local: true do |f| %>
  <div class="form-group">
    <label>タイトル</label>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <label>収支ステータス</label>
    <%= f.select(:status, {収入: 'income', 支出: 'outcome'}, {class: "form-control"}) %>
  </div>
  <div class="form-group">
    <label>支払先</label>
    <%= f.text_field :payee, class: "form-control" %>
  </div>
  <div class="form-group">
    <label>会計係</label>
    <%= f.text_field :treasurer, class: "form-control" %>
  </div>
  <div class="form-group">
    <label>受取日</label>
    <%= f.date_select :received_day, use_month_numbers: true, start_year: 1970, end_year: Time.now.year, class: "form-control" %>
  </div>
  <div class="form-group" id="return_day_area">
    <label>返金日</label>
    <%= f.date_select :return_day, use_month_numbers: true, start_year: 1970, end_year: Time.now.year, prompt: "--", class: "form-control" %>
  </div>
  <div class="form-group">
    <label>金額</label>
    <%= f.text_field :price, class: "form-control" %>
  </div>
  <div class="form-group">
    <label>画像</label>
    <%= f.file_field :image, class: "form-control" %>
    <%= image_tag @history.image.path.to_s %>
    <%= f.hidden_field :image_cache %>
  </div>
  <div class="form-group">
    <label>内容</label>
    <%= f.text_area :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit "保存", class: "btn btn-primary" %>
  </div>
<% end %>

<style>
  div.form-group {
    width: 900px;
    text-align: center;
  }
</style>

app/views/histories/edit.html.erb
<div>
  <div class="form-group">
    <h2 class="text-center">会計履歴編集</h2>
    <%= render 'form' %>
  </div>
</div>

<style>
  div.form-group {
    width: 900px;
    text-align: center;
  }
</style>

app/views/histories/index.html.erb
<h2>会計管理アプリ</h2>
<div class="row width">
  <div class="col-md-12">
    <table class="colums">
      <% if @histories.present? %>
        <thead class="thead-light">
          <tr>
            <th>タイトル</th>
            <th>カテゴリ</th>
            <th>金額</th>
            <th>支払先</th>
            <th>会計係</th>
            <th>領収書受取日</th>
            <th>返却日</th>
            <th>内容</th>
            <th>ステータス</th>
            <th>処理内容</th>
          </tr>
        </thead>
        <tbody>
          <% @histories.each do |history| %>
            <tr>
              <td><%= link_to history.title, history_path(history) %></td>
              <td><%= history.category %></td>
              <td><%= history.price %></td>
              <td><%= history.payee %></td>
              <td><%= history.treasurer %></td>
              <td><%= history.received_day&.to_date %></td>
              <td><%= history.return_day&.to_date %></td>
              <td><%= history.description %></td>
              <td><%= history.status %></td>
              <td>[ <%= link_to '編集',  edit_history_path(history) %> ] 
                  [ <%= link_to '削除', history_path(history), method: :delete, data:{ confirm: '削除してよろしいですか?' } %> ]
              </td>
            </tr>
          <% end %>
        </tbody>
      <% else %>
          <p>現在会計履歴はありません</p>
      <% end %>
    </table>
  </div>
  <h3>収支集計</h3>
  <div class="col-md-12">
    <table class="colums">
      <% if @histories.present? %>
        <thead class="thead-light">
          <tr>
            <th>合計金額</th>
            <th>収入合計</th>
            <th>支出合計</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= "#{@total_price}円" %></td>
            <td><%= "#{@total_income}円" %></td>
            <td><%= "#{@total_outcome}円" %></td>
          </tr>
        </tbody>
      <% else %>
          <p>現在会計履歴はありません</p>
      <% end %>
    </table>
  </div>
</div>
<style>
  div.width {
    width: 1000px;
  }
  
  table.colums {
    border-collapse: collapse;
    border: 1px solid #dcdcdc;
  }
  
  table.colums th{
    border: 1px solid #dcdcdc;
    background: #deb887;
    font-size: 15px;
    padding: 4px;
  }
 
  table.colums td{
    border:1px solid #dcdcdc;
    background:#ffffff;
    font-size: 13px;
  }
  
</style>

app/views/histories/new.html.erb
<div>
  <div class="form-group">
    <h2 class="text-center">新規履歴作成</h2>
    <%= render 'form' %>
  </div>
</div>

<style>
  div.form-group {
    width: 900px;
    text-align: center;
  }
</style>

app/views/histories/search.html.erb
<h2>会計履歴検索</h2>
<div class="row width">
  <div class="col-md-12">
    <%= form_with(scope: :search, url: search_histories_path, method: :get, local: true) do |f| %>
      <div class="form-group">
        <label>タイトル</label>
        <%= f.text_field :title, value: params[:title], class: 'form-control' %>
      </div>
      <div class="form-group">
        <label>カテゴリ</label>
        <%= f.text_field :category, value: params[:category], class: 'form-control' %>
      </div>
      <div class="form-group">
        <label>収支ステータス</label>
        <%= f.select :status, options_for_select([['収入', 0],['支出', 1]], params[:status]), {:prompt => "--"}, {:class => 'form-control'} %>
      </div>
      <div class="form-group">
        <label>金額</label>
        <%= f.text_field :price, value: params[:price],  class: 'form-control' %>円
      </div>
      <div class="form-group">
        <label>支払先</label>
        <%= f.text_field :payee, value: params[:payee], class: 'form-control' %>
      </div>
      <div class="form-group">
        <label>会計係</label>
        <%= f.text_field :treasurer, value: params[:treasurer], class: 'form-control' %>
      </div>
      <div class="form-group">
        <label>対象受取期間</label>
        <%= f.date_field :start_received_day, value: params[:start_received_day], use_month_numbers: true, prompt: "--", class: 'form-control' %> ~
        <%= f.date_field :finish_received_day, value: params[:finish_received_day], use_month_numbers: true, prompt: "--", class: 'form-control' %>
      </div>
      <div class="form-group" id="return_day_area">
        <label>対象返却期間</label>
        <%= f.date_field :start_return_day, value: params[:start_return_day], use_month_numbers: true, prompt: "--", class: 'form-control' %> ~
        <%= f.date_field :finish_return_day, value: params[:finish_return_day], use_month_numbers: true, prompt: "--", class: 'form-control' %>
      </div>
      <div class="text-center">
        <%= f.submit "検索", class: 'btn btn-primary' %>
      </div>
    <% end %>
    
    <table class="colums">
      <% if @histories.present? %>
        <thead class="thead-light">
          <tr>
            <th>タイトル</th>
            <th>カテゴリー</th>
            <th>金額</th>
            <th>支払先</th>
            <th>会計係</th>
            <th>領収書受取日</th>
            <th>返却日</th>
            <th>内容</th>
            <th>ステータス</th>
            <th>処理内容</th>
          </tr>
        </thead>
        <tbody>
          <% @histories.each do |history| %>
            <tr>
              <td><%= history.title %></td>
              <td><%= history.category %></td>
              <td><%= history.price %></td>
              <td><%= history.payee %></td>
              <td><%= history.treasurer %></td>
              <td><%= history.received_day&.to_date %></td>
              <td><%= history.return_day&.to_date %></td>
              <td><%= history.description %></td>
              <td><%= history.status %></td>
              <td>[ <%= link_to '編集',  edit_history_path(history) %> ] 
                  [ <%= link_to '削除', history_path(history), method: :delete, data:{ confirm: '削除してよろしいですか?' } %> ]
              </td>
            </tr>
          <% end %>
        </tbody>
      <% else %>
          <p>検索結果がありません</p>
      <% end %>
    </table>
  </div>
</div>
<style>
  div.width {
    width: 1000px;
  }
  
  table.colums {
    order-collapse: collapse;
    border: 1px solid #dcdcdc;
  }
  
  table.colums th{
    border: 1px solid #dcdcdc;
    background: #deb887;
    font-size: 15px;
    padding: 4px;
  }
 
  table.colums td{
    border:1px solid #dcdcdc;
    background:#ffffff;
    font-size: 13px;
  }
  
</style>

app/views/histories/show.html.erb
<div class="row">
  <div class="col-md-12">
    <h2><%= @history.title %></h2>
    <div>
      金額: <%= @history.price %>円
    </div>
    <div>
      <% if @history.image? %>
        画像：<%= image_tag @history.image.url %>
      <% else %>
        画像: 画像なし
      <% end %>
    </div>
    <div>
      支払先: <%= @history.payee %>
    </div>
    <div>
      会計係: <%= @history.treasurer %>
    </div>
    <div>
      内容: <%= @history.description %>
    </div>
    <hr>
    
    <h3>質問</h3>
    <div class="row width">
      <table class="colums">
        <% if @history.questions.any? %>
          <thead class="thead-light">
            <tr>
              <td>タイトル</td>
              <td>質問者</td>
              <td>内容</td>
              <td>処理内容</td>
            </tr>
          </thead>
          <tbody>
            <% @history.questions.each do |question| %>
              <tr>
                <td>
                  <%= question.title %>
                </td>
                <td>
                  <%= question.name %>
                </td>
                <td>
                  <%= question.content %>
                </td>
                <td>
                  [<%= link_to '編集', edit_history_question_path(@history, question) %>]
                  [<%= link_to '削除', history_question_path(@history, question), 
                    method: :delete, data:{ confirm: '本当に削除してよろしいですか?'} %> ]
                </td>
              </tr>
            <% end %>
          </tbody>
        <% else %>
          <p>現在質問はありません</p>
        <% end %>
      </table>
    </div>
    
    <h3>質問を作成できます</h3>
    
    <%= form_with model: [@history, @question], local: true do |f| %>
      <%= f.hidden_field :history_id, { value: @history.id} %>
      <div class="form-group">
        <label>タイトル</label>
        <%= f.text_field :title, class: 'form-control' %>
      </div>
      <div class="form-group">
        <label>質問者</label>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
      <div class="form-group">
        <label>内容</label>
        <%= f.text_area :content, class: 'form-control' %>
      </div>
      <div class="text-center">
        <%= f.submit "保存", class: 'btn btn-primary' %>
      </div>
    <% end %>
    
    <div>
      <%= link_to '> トップへ戻る', root_path %>
    </div>
  </div>
</div>

<style>
  div.width {
    width: 1000px;
  }
  
  table.colums {
    border-collapse: collapse;
    border: 1px solid #dcdcdc;
  }
  
  table.colums th{
    border: 1px solid #dcdcdc;
    background: #deb887;
    font-size: 15px;
    padding: 4px;
  }
 
  table.colums td{
    border:1px solid #dcdcdc;
    background:#ffffff;
    font-size: 13px;
  }
</style>

app/views/layouts/_sidebar.html.erb
<div class="sidebar right">
  <table class="sidebar__search__box">
    <tbody>
      <tr>
        <td class="sidebar__search__box__name">
          <%= link_to 'ホーム画面', root_path %>
        </td>
      </tr>
      <tr>
        <td class="sidebar__search__box__name">
          <%= link_to '新規履歴作成', new_history_path %>
        </td>
      </tr>
      <tr>
        <td class="sidebar__search__box__name">
          <%= link_to '検索機能', search_histories_path %>
        </td>
      </tr>
    </tbody>
  </table>
</div>
<script>
  $(document).ready(function () {
    // 向き
    var sides = ["right"];
    // サイドバーの初期化
    for (var i = 0; i <script sides.length; ++i) {
      var cSide = sides[i];
      $(".sidebar." + cSide).sidebar({side: cSide});
    }
    // ボタンのクリックにより...
    $(".btn[data-action]").on("click", function () {
      var $this = $(this);
      var action = $this.attr("data-action");
      var side = $this.attr("data-side");
      $(".sidebar." + side).trigger("sidebar:" + action);
      return false;
    });
  });
</script>
<style>
  .sidebar{
    position: fixed;
    color: #B0E0E6;
    text-align: left;
    padding: 12px;
  }
 
    .sidebar.left {
      top: 0;
      left: 0;
      bottom: 0;
      width: 150px;
      background: #FFFACD;
    }
 
    .sidebar.right {
      top: 0;
      right: 0;
      bottom: 0;
      width: 120px;
      background: #FAF0E6;
    }
 
    .sidebar.top {
      left: 0;
      right: 0;
      top: 0;
      height: 150px;
      background: #FFFACD;
    }
 
    .sidebar.bottom {
      left: 0;
      right: 0;
      bottom: 0;
      height: 150px;
      background: #FFFACD;
    }
    
</style>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Treasurer_app</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag 'https://kit.fontawesome.com/3b011d839e.js' %>
    <%= javascript_include_tag 'https://code.jquery.com/jquery-1.12.3.min.js' %>
    <%= javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/jquery-sidebar/3.3.2/jquery.sidebar.min.js' %>
  </head>

  <body>
    <div class="container">
      <% if flash[:notice] %>
        <p class="text-success"><%= flash[:notice] %></p>
      <% end %>
      <% if flash[:alert] %>
        <p class="text-danger"><%= flash[:alert] %></p>
      <% end %>
      
      <%= render 'layouts/sidebar' %>
      
      <%= yield %>
    </div>
  </body>
</html>

app/views/questions/edit.html.erb
<div>
  <h2>質問編集</h2>
  <%= form_with model:[@history, @question], local: true do |f| %>
    <div class="form-group">
      <div class="form-group">
        <label>タイトル</label>
        <%= f.text_field :title, class:"form-control" %>
      </div>
      <div class="form-group">
        <label>質問者</label>
        <%= f.text_field :name, class:"form-control" %>
      </div>
      <div class="form-group">
        <label>内容</label>
        <%= f.text_area :content, class:"form-control" %>
      </div>
      <div class="text-center">
        <%= f.submit "作成", class: "btn btn-primary" %>
      </div>
    </div>
  <% end %>
</div>